### ISSUE TITLE
QLORA -4bit

### ISSUE THREAD

**Issue by seroetr** [princeton-nlp/SimPO#14]
Does Simpo support Qlora fine-tuning using 4bit for Llama-3-8B ?
if so, how to set it up?

**Comment by yumeng5** [comment]
Since our repo is based on [alignment-handbook](https://github.com/huggingface/alignment-handbook), I believe it'll be straightforward to integrate LoRA/QLoRA fine-tuning by following their [QLoRA training examples](https://github.com/huggingface/alignment-handbook/tree/main/recipes/zephyr-7b-beta#qlora-training-examples). We're working on a PR to add SimPO to alignment-handbook which hopefully will make it easier to deploy PEFT.

Best,
Yu
