### ISSUE TITLE
Unable to reproduce the mt bench results in the paper

### ISSUE THREAD

**Issue by lmx760581375** [princeton-nlp/SimPO#22]
When I downloaded checkpoint published by you on huggingface, I used the following command to test mt bench. The 7.04 obtained by GPT4 evaluation is not consistent with the 7.3 in your article. How can I replicate the MT-bench result?

model: https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-SimPO
testset: MT-bench （https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/）

```
python3 gen_model_answer.py --model-path llm_models/Mistral-7B-Base-SFT-SimPO  --model-id Mistral-7B-Base-SFT-SimPO
python3 gen_judgment.py --model-list Mistral-7B-Base-SFT-SimPO --parallel 10
```

**Comment by yumeng5** [comment]
Hi,

I believe it's because the chat template has not been appropriately applied for MT-Bench eval.

For our Mistral-Base setup, we used the chat template same as Zephyr
https://github.com/princeton-nlp/SimPO/blob/baf9b8428dc1d602de1801a4e19dde295916cea7/chat_templates.json#L4

MT-Bench evaluation applies chat templates based on string matching of model names:
https://github.com/lm-sys/FastChat/blob/c5223e34babd24c3f9b08205e6751ea6e42c9684/fastchat/model/model_adapter.py#L2054

Therefore, to ensure that the chat template is appropriately applied, you need to have "Zephyr" not "Mistral" in `--model-id`. You can replace `Mistral-7B-Base-SFT-SimPO` with `Zephyr-7B-Base-SFT-SimPO` when you run `gen_model_answer.py`.

I hope this helps! Let us know if there are further issues.

Best,
Yu
