### ISSUE TITLE
Your comparsion is unfair by using different chat templates

### ISSUE THREAD

**Issue by AGTSAAA** [princeton-nlp/SimPO#24]
In your checkpoint: [princeton-nlp/Mistral-7B-Base-SFT-SimPO](https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-SimPO), the chat_template is:

"chat_template": "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}",

However, the base model [alignment-handbook/zephyr-7b-sft-full](https://huggingface.co/alignment-handbook/zephyr-7b-sft-full) has a different template:

"chat_template": "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<\|user\|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<\|system\|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<\|assistant\|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<\|assistant\|>' }}\n{% endif %}\n{% endfor %}",

Why did you change the chat_template when you fine-tuned the [alignment-handbook/zephyr-7b-sft-full](https://huggingface.co/alignment-handbook/zephyr-7b-sft-full)?

Based on my experiments, the training chat template largely affects the performance on AlpacaEval2 (the most important contribution in your paper).

**Comment by yumeng5** [comment]
Hi,

We didn't change the chat template under the Mistral-Base setup. Please refer to our chat templates used for each setting: https://github.com/princeton-nlp/SimPO/blob/baf9b8428dc1d602de1801a4e19dde295916cea7/chat_templates.json#L4

This is exactly the Zephyr chat template. I'm not sure why our released checkpoints have a different chat template and I think it's likely due to an incorrect `tokenizer_config.json` file being uploaded. We are looking into this and will fix it soon.

Putting this issue aside, I don't think changing `chat_template` in training makes the comparisons unfair (again, we didn't change it in our experiments) -- as long as the `chat_template` used in decoding is consistent with the one in training, the model's performance shouldn't be affected.

Best,
Yu

**Comment by xiamengzhou** [comment]
Hi @AGTSAAA,

Thanks for catching this! To clarify, for models that start with `Mistral-7b-Base` in our released collection, we use the Zephyr template for training and evaluation as expected. However, during the upload process, I mistakenly copied the Mistral-Instruct tokenizer files into the model folder, which included the incorrect chat template. This error has been corrected; you can find the commit [here](https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-SimPO/commit/fe8c3ca9cd73310570db10c836e9c00b440acf5a). Templates for other models under the Mistral-7b-Base setting are also fixed. Let me know if it helps and happy to assist with your further enquiries. 

Mengzhou
