### ISSUE TITLE
On-Policy Preference Data Generation

### ISSUE THREAD

**Issue by tannedbum** [princeton-nlp/SimPO#62]
Decoded 3 seeds. The 2nd and 3rd generated response are under the wrong prompt after post_process.py. I haven't touched the code. What am I doing wrong ?

HuggingFaceH4/ultrafeedback_binarized

Happens with all llama 3 & 3.1, mistral and nemo.

I decoded the seeds one by one. Using runpod and cuda 12.4 image. I also build vllm from the source but didn't solve the problem.

![ugh](https://github.com/user-attachments/assets/eccebe6f-ad3a-4682-96d7-8602901d0602)

**Comment by yumeng5** [comment]
Hi @tannedbum 

Thanks for reporting the issue. It looks like it is due to the randomness in preprocessing the dataset. In the latest commit, I have added a sorted operation for the prompts which should have fixed the issue.

If you still have your `output_{seed}.json` files, you don't have to re-run the decoding step, but instead, post-process your `output_{seed}.json` files so that the order of the prompts is kept the same across different seeds. After that, you can run steps 2 and 3 in the [README file](https://github.com/princeton-nlp/SimPO/blob/main/on_policy_data_gen/README.md) which should yield the on-policy training set.

Let me know if you still encounter any issues.

Best,
Yu

**Comment by tannedbum** [comment]
Nice work. Thank you so much for fixing the code. Confirmed, it now works as intended.
