### ISSUE TITLE
About SFT

### ISSUE THREAD

**Issue by XYaoooo** [princeton-nlp/SimPO#72]
Hi authors,
 It seems you do SFT training on the instruction + response, rather than response (p(response|instruction))，right?
Do you know the difference of performance on instruction following it caused?
Thanks.

**Comment by yumeng5** [comment]
Hi,

Yes, we followed the SFT trainer logic in the original alignment-handbook repo which trains on all tokens.

We observed mixed results of training on all tokens vs. training on response tokens only, but the differences were not very significant. Due to the simplicity of training on all tokens (no need to mask out prompt tokens), we adopted that implementation.

I hope this helps.

Best,
Yu

**Comment by XYaoooo** [comment]
Thx
