### ISSUE TITLE
Mismatch of results

### ISSUE THREAD

**Issue by AGTSAAA** [princeton-nlp/SimPO#9]
Hi, I use the following command to run the code

CUDA_VISIBLE_DEVICES=3,5,6 ACCELERATE_LOG_LEVEL=info accelerate launch --config_file accelerate_configs/deepspeed_zero3.yaml scripts/run.py training_configs/mistral-7b-base-simpo.yaml

I found that it occupies 70GB per A100 card, even when the batch size is set to 1.

Could you help me with this? Why does it occupy so much GPU memory even with deepspeed_zero3?"

**Comment by yumeng5** [comment]
Hi,

I suppose you are using 3 GPUs for running the code. The original scripts we used were set for 8 GPUs, and the per device batch size can be set to 4 with 80GB GPUs. If you have fewer GPUs, it's normal for the GPU memory consumption to be higher. Additionally, it's recommended to use either 2 or 4 GPUs instead of 3 because achieving a global batch size of 128 is difficult with 3 GPUs.

Best,
Yu

**Comment by yumeng5** [comment]
Hi, 

This is because our DPO checkpoint under the Mistral-base setup is different from the [Zephyr checkpoint](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta). 

There was an update of the Zephyr training recipe in hyperparameters such as `beta` and `num_train_epochs` ~5 months ago (see [here](https://github.com/huggingface/alignment-handbook/pull/88)). However, the [model checkpoint](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) was not updated as far as I know. 

Therefore, we trained our own DPO model under the Mistral-base setup with the updated hyperparameters of the Zephyr training recipe. We found that this new DPO model indeed led to better instruction-following scores (our DPO checkpoint has 15.1 LC win rate and 12.5 raw win rate on AlpacaEval 2 as reported in our paper, while the official Zephyr checkpoint has 13.2 LC win rate and 11.0 raw win rate according to the [AlpacaEval 2 Leaderboard](https://tatsu-lab.github.io/alpaca_eval/). 

It's normal for instruction-following scores not to always correlate positively with downstream task scores on the Open LLM Leaderboard. We believe this tradeoff is mostly due to different hyperparameter choices, and it applies similarly to all the baselines we compared against. Given our focus on preference optimization, we prioritize instruction-following benchmarks over Open LLM Leaderboard tasks.

Let us know if you have further questions.

Best,
Yu

**Comment by xiamengzhou** [comment]
@AGTSAAA We use the lm-evaluation-harness for evaluation and follow the settings in open-llm-leaderboard!

**Comment by xiamengzhou** [comment]
We used [this version](https://github.com/EleutherAI/lm-evaluation-harness/tree/b281b0921b636bc36ad05c0b0b0763bd6dd43463) as the open-llm-leaderboard suggested.

**Comment by AIR-hl** [comment]
@xiamengzhou Hi! I tried to evaluate  [Mistral-7B-Base-SFT-SimPO](https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-SimPO),  [Mistral-7B-Base-SFT-DPO](https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-DPO) and [Mistral-7B-Base-SFT-RDPO](https://huggingface.co/princeton-nlp/Mistral-7B-Base-SFT-RDPO) on `GSM8K` through [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)

I use the default `gsm8k` task and `vllm` as follows:
```
lm_eval --model vllm \
    --model_args pretrained=${model_name},tensor_parallel_size=0,dtype=bfloat16,gpu_memory_utilization=0.9,data_parallel_size=0 \
    --tasks gsm8k \
    --num_fewshot 5 \
    --apply_chat_template \
    --batch_size auto
```

but I get a strange result that `dpo` is much better than the others, so I want to know is there something wrong?

|simpo|dpo|rdpo|
|----|----|----|
|0.1729|0.2540|0.1993|
